# Question 8

In [ ]:
from sklearn import svm
import numpy as np

In [ ]:
X = np.array(
    [
        [0.4, 0.3],
        [0.8, 0.7],
        [0.3, 0.3],
        [0.7, 0.6],
        [0.9, 0.7],
        [0.3, 0.4],
        [0.6, 0.7]
    ]
)

In [ ]:
Y = np.array([-1, 1, -1, 1, 1, -1, 1])

In [ ]:
model = svm.SVC(C = 1.0, kernel = 'linear', probability = True, max_iter = 300)

In [ ]:
model.fit(X, Y)

SVC(kernel='linear', max_iter=300, probability=True)

In [ ]:
print("Predicted value: ", model.predict_proba(np.array([[0.3, 0.4]])))

Predicted value:  [[0.38192434 0.61807566]]


# Question 3

In [ ]:
import numpy as np

In [ ]:
class Fuzzy:

  def __init__(self):
    pass

  def union(self, set1, set2):
    return np.maximum(set1, set2)

  def intersection(self, set1, set2):
    return np.minimum(set1, set2)

  def complement(self, set1):
    return 1 - set1

  def composition_complement(self, relation):
    return 1 - relation

  def min_max_composition(self, relation, set1):
    return np.sum(relation*set1, axis = 1)


In [ ]:
fuzzyOops = Fuzzy()

In [ ]:
set1 = np.array([0.3, 0.5, 0.2])
set2 = np.array([0.1, 0.6, 0.8])

In [ ]:
relation = np.array(
    [
        [0.4, 0.2, 0.7],
        [0.2, 0.9, 0.6],
        [0.4, 0.6, 0.3]
    ]
)

In [ ]:
print("Set1: ", set1)
print("Set2: ", set2)
print("Relation: ", relation)

Set1:  [0.3 0.5 0.2]
Set2:  [0.1 0.6 0.8]
Relation:  [[0.4 0.2 0.7]
 [0.2 0.9 0.6]
 [0.4 0.6 0.3]]


In [ ]:
print("Union: ", fuzzyOops.union(set1, set2))
print("Intersection: ", fuzzyOops.intersection(set1, set2))
print("Complement: ", fuzzyOops.complement(set1))
print(": ", fuzzyOops.complement(set1))
print("Relation complement: ", fuzzyOops.composition_complement(relation))
print("Max min Composition: ", fuzzyOops.min_max_composition(relation, set1))

Union:  [0.3 0.6 0.8]
Intersection:  [0.1 0.5 0.2]
Complement:  [0.7 0.5 0.8]
:  [0.7 0.5 0.8]
Relation complement:  [[0.6 0.8 0.3]
 [0.8 0.1 0.4]
 [0.6 0.4 0.7]]
Max min Composition:  [0.36 0.63 0.48]
