In [1]:
import numpy as np

In [6]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
type(a)

numpy.ndarray

In [11]:
b = np.array([range(1, 10)])
print(len(b))
print(b.size)
print(type(b))

1
9
<class 'numpy.ndarray'>


In [14]:
c = np.array([[1,2,3,4],[5,6,7,8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
c.ndim # number of dim

2

In [31]:
np.random.rand(8).reshape(2,2,2).ndim

3

In [30]:
c.ndim == len(c.shape)

True

In [33]:
d = np.array([[1,2,3],[5,6,7],[8,9,10]])
d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [38]:
np.random.rand(9).reshape(1,3,3)

array([[[0.65168834, 0.5489385 , 0.85893636],
        [0.6037971 , 0.48607488, 0.38855366],
        [0.61284033, 0.62525329, 0.29083502]]])

In [41]:
np.random.random((10, 4))

array([[0.17071038, 0.1756023 , 0.53991541, 0.05514476],
       [0.15313438, 0.22242515, 0.85809831, 0.79985514],
       [0.37146258, 0.00157861, 0.18389548, 0.31825686],
       [0.80707999, 0.29701571, 0.49131049, 0.19919908],
       [0.24139382, 0.3288808 , 0.14699517, 0.5837658 ],
       [0.90088349, 0.50046189, 0.97500071, 0.10745804],
       [0.34040759, 0.97444593, 0.4859654 , 0.48844274],
       [0.91169127, 0.88055119, 0.20529404, 0.33683898],
       [0.78020022, 0.00539589, 0.72319473, 0.22491644],
       [0.70100468, 0.06957335, 0.14071756, 0.99285705]])